Repository AutoDevLog/AutoDevLog-Server, pull requests merged in 2024-06, with the labels that each got.

#34 [Fix] 토큰 만료 기한 재설정, JWT Service 리팩토링
  src/main/java/com/server/autodevlog/auth/service/JwtService.java
  src/main/java/com/server/autodevlog/auth/service/JwtString.java
Labels: :bug:Debug

#38 [Refactor/37] GPT API 호출시 System prompt 수정 + GPT Controller reponse dto 도입/변경
  src/main/java/com/server/autodevlog/gpt/controller/GPTController.java
  src/main/java/com/server/autodevlog/gpt/dto/ChatGptRequest.java
  src/main/java/com/server/autodevlog/gpt/dto/UserResponseDto.java
Labels: :recycle:Refactoring

#36 [Fix] retry 적용과 리팩토링
  build.gradle
  src/main/java/com/server/autodevlog/AutoDevLogApplication.java
  src/main/java/com/server/autodevlog/auth/domain/Member.java
  src/main/java/com/server/autodevlog/auth/service/JwtEnum.java
  src/main/java/com/server/autodevlog/auth/service/JwtService.java
  src/main/java/com/server/autodevlog/auth/service/JwtString.java
  src/main/java/com/server/autodevlog/blog/controller/BlogController.java
  src/main/java/com/server/autodevlog/blog/service/BlogService.java
Labels: :bug:Debug, :recycle:Refactoring

#40 [Feat/39] GPT API 생성 Article Upload API
  src/main/java/com/server/autodevlog/blog/controller/BlogController.java
  src/main/java/com/server/autodevlog/blog/dto/ArticleUploadRequestDto.java
  src/main/java/com/server/autodevlog/blog/service/BlogService.java
  src/main/java/com/server/autodevlog/gpt/controller/GPTController.java
  src/main/java/com/server/autodevlog/gpt/domain/Article.java
  src/main/java/com/server/autodevlog/gpt/repository/ArticleRepository.java
  src/main/java/com/server/autodevlog/gpt/service/ArticleService.java
Labels: :sparkles:Feature

#42 [Refactor/41] WAS GPT ARTICLE POST API 리팩토링
  src/main/java/com/server/autodevlog/blog/controller/BlogController.java
  src/main/java/com/server/autodevlog/global/exception/ErrorCode.java
  src/main/java/com/server/autodevlog/gpt/controller/GPTController.java
  src/main/java/com/server/autodevlog/gpt/domain/GPTArticle.java
  src/main/java/com/server/autodevlog/gpt/dto/GPTArticleUploadRequestDto.java
  src/main/java/com/server/autodevlog/gpt/repository/ArticleRepository.java
  src/main/java/com/server/autodevlog/gpt/repository/GPTArticleRepository.java
  src/main/java/com/server/autodevlog/gpt/service/ArticleService.java
  src/main/java/com/server/autodevlog/gpt/service/GPTArticleService.java
Labels: :recycle:Refactoring

#46 [Feat] 글 작성시 URL을 함께 리턴
  src/main/java/com/server/autodevlog/blog/controller/BlogController.java
  src/main/java/com/server/autodevlog/blog/dto/PostingResultDto.java
  src/main/java/com/server/autodevlog/blog/dto/VelogPostResponseDto.java
  src/main/java/com/server/autodevlog/blog/service/BlogService.java
Labels: :sparkles:Feature
