Repository AutoDevLog/AutoDevLog-Server, pull requests merged in 2024-05, with the labels that each got.

#2 [Feat] gpt api 연동 구현
  src/main/java/com/server/autodevlog/global/exception/CustomException.java
  src/main/java/com/server/autodevlog/global/exception/CustomExceptionHandler.java
  src/main/java/com/server/autodevlog/global/exception/ErrorCode.java
  src/main/java/com/server/autodevlog/global/exception/ErrorResponseEntity.java
  src/main/java/com/server/autodevlog/gpt/config/OpenAiConfig.java
  src/main/java/com/server/autodevlog/gpt/controller/GPTController.java
  src/main/java/com/server/autodevlog/gpt/convertor/GptConvertor.java
  src/main/java/com/server/autodevlog/gpt/dto/ChatGptRequest.java
  src/main/java/com/server/autodevlog/gpt/dto/ChatGptResponse.java
  src/main/java/com/server/autodevlog/gpt/dto/Message.java
  src/main/java/com/server/autodevlog/gpt/dto/UserRequestDto.java
  src/main/java/com/server/autodevlog/gpt/dto/UserResponseDto.java
Labels: :sparkles:Feature

#4 [Feat] 벨로그 업로드 API
  src/main/java/com/server/autodevlog/blog/controller/BlogController.java
  src/main/java/com/server/autodevlog/blog/dto/VelogPostDto.java
  src/main/java/com/server/autodevlog/blog/service/BlogService.java
  src/main/java/com/server/autodevlog/config/SwaggerConfig.java
Labels: :sparkles:Feature

#13 [Refactor] Velog 포스팅 API 예외처리 및 컨트롤러 테스트 코드 작성
  build.gradle
  src/main/java/com/server/autodevlog/blog/controller/BlogController.java
  src/main/java/com/server/autodevlog/blog/dto/VelogPostRequestDto.java
  src/main/java/com/server/autodevlog/blog/dto/VelogPostResponseDto.java
  src/main/java/com/server/autodevlog/blog/service/BlogService.java
  src/main/java/com/server/autodevlog/global/exception/ErrorCode.java
  src/test/java/com/server/autodevlog/blog/BlogControllerTest.java
Labels: :recycle:Refactoring

#16 Feat/12 RequestBody 프롬프트 issue/inference/solution 3단 구조 도입
  src/main/java/com/server/autodevlog/gpt/controller/GPTController.java
  src/main/java/com/server/autodevlog/gpt/convertor/EmbeddingConvertor.java
  src/main/java/com/server/autodevlog/gpt/convertor/GptConvertor.java
  src/main/java/com/server/autodevlog/gpt/dto/ChatGptRequest.java
  src/main/java/com/server/autodevlog/gpt/dto/UserRequestDto.java
  src/main/java/com/server/autodevlog/gpt/dto/UserResponseDto.java
Labels: :sparkles:Feature

#25 request dto Annotation validation 적용
  build.gradle
  src/main/java/com/server/autodevlog/global/exception/ErrorCode.java
  src/main/java/com/server/autodevlog/gpt/controller/AnalyzeController.java
  src/main/java/com/server/autodevlog/gpt/controller/GPTController.java
  src/main/java/com/server/autodevlog/gpt/dto/AnalyzeRequest.java
  src/main/java/com/server/autodevlog/gpt/dto/UserRequestDto.java
  src/main/java/com/server/autodevlog/gpt/validation/NullPrompt.java
  src/main/java/com/server/autodevlog/gpt/validation/PromptValidator.java
Labels: :recycle:Refactoring

#27 [FIX] 포스팅 API 응답 오류 수정
  src/main/java/com/server/autodevlog/auth/service/AuthService.java
  src/main/java/com/server/autodevlog/blog/dto/VelogPostResponseDto.java
  src/main/java/com/server/autodevlog/blog/service/BlogService.java
Labels: :bug:Debug
